package tools

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/md5"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"html"
	"io"
	"net/http"
	"net/url"
	"sync"
	"time"
)

type storageProviderS3 struct {
	AccessKey string // Access Key ID
	SecretKey string // Access Key Secret
	Endpoint  string // S3 Endpoint
	Region    string // S3 Region
	Bucket    string // S3 Bucket
	Host      string // To be filled from Endpoint Field
}

func (o *storageProviderS3) Start(stop context.Context, await *sync.WaitGroup) error {

	// Prepare Client
	s3url, err := url.Parse(STORAGE_S3_ENDPOINT)
	if err != nil {
		return fmt.Errorf("invalid s3 endpoint url; %s", err)
	}
	o.AccessKey = STORAGE_S3_KEY_ACCESS
	o.SecretKey = STORAGE_S3_KEY_SECRET
	o.Endpoint = STORAGE_S3_ENDPOINT
	o.Region = STORAGE_S3_REGION
	o.Bucket = STORAGE_S3_BUCKET
	o.Host = s3url.Host

	// Test Client
	ctx, cancel := context.WithTimeout(context.Background(), TIMEOUT_CONTEXT)
	defer cancel()

	filename := fmt.Sprintf("_test/__%d__", GenerateSnowflake())
	filedata := "Don't worry you aren't being hacked!" +
		" This file was generated by the backend on startup to ensure it has write access to the S3 Bucket." +
		" If you're seeing this most likely the process was killed during startup." +
		" You can safely delete me :)"

	if err := o.Put(ctx, filename, "text/plain", bytes.NewReader([]byte(filedata))); err != nil {
		return fmt.Errorf("missing write access; %s", err)
	}
	if err := o.Delete(ctx, filename); err != nil {
		return fmt.Errorf("missing delete access: %s", err)
	}

	return nil
}

func (o *storageProviderS3) Put(ctx context.Context, key, contentType string, r io.ReadSeeker) error {

	// Generate Hashes
	hashLen := int64(0)
	hashMD5 := md5.New()
	hashSHA := sha256.New()
	if l, err := io.Copy(io.MultiWriter(hashMD5, hashSHA), r); err != nil {
		return nil
	} else {
		hashLen = l
	}
	if _, err := r.Seek(0, io.SeekStart); err != nil {
		return err
	}

	// Generate Request
	url := (o.Endpoint + "/" + key)
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, url, r)
	if err != nil {
		return err
	}
	req.Header.Add("Content-Type", contentType)
	req.ContentLength = hashLen
	amazonSignRequestV4(
		req, hashMD5.Sum(nil), hashSHA.Sum(nil),
		o.AccessKey, o.SecretKey, o.Host, o.Region, "s3",
	)

	// Send Request
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer res.Body.Close()

	if res.StatusCode < 200 || res.StatusCode > 299 {
		body, _ := io.ReadAll(res.Body)
		return fmt.Errorf("put failed: %d: %s", res.StatusCode, string(body))
	}

	return nil
}

func (o *storageProviderS3) Delete(ctx context.Context, keys ...string) error {

	// Generate Hashes
	str := bytes.Buffer{}
	str.WriteString("<Delete xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">")
	for _, k := range keys {
		fmt.Fprintf(&str, "<Object><Key>%s</Key></Object>", html.EscapeString(k))
	}
	str.WriteString("</Delete>")

	buf := str.Bytes()
	hashMD5 := md5.Sum(buf)
	hashSHA := sha256.Sum256(buf)

	// Generate Request
	url := (o.Endpoint + "/?delete")
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, &str)
	if err != nil {
		return err
	}
	amazonSignRequestV4(
		req, hashMD5[:], hashSHA[:],
		o.AccessKey, o.SecretKey, o.Host, o.Region, "s3",
	)

	// Send Request
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer res.Body.Close()

	if res.StatusCode < 200 || res.StatusCode > 299 {
		body, _ := io.ReadAll(res.Body)
		return fmt.Errorf("server responded with status %d: %s", res.StatusCode, string(body))
	}

	return nil
}

// Applies relevant headers for AWS Signature Version 4
func amazonSignRequestV4(
	req *http.Request, hashMD5, hashSHA256 []byte,
	accessKey, secretKey, host, region, service string,
) {
	// Timestamp
	t := time.Now().UTC()
	dateStamp := t.Format("20060102")
	dataAmazon := t.Format("20060102T150405Z")

	// Hash Content
	stringSHA := hex.EncodeToString(hashSHA256)
	stringMD5 := base64.StdEncoding.EncodeToString(hashMD5)

	// Apply Headers
	req.Header.Set("Host", host)
	req.Header.Set("Content-MD5", stringMD5)
	req.Header.Set("x-amz-date", dataAmazon)
	req.Header.Set("x-amz-content-sha256", stringSHA)
	req.Host = host

	// 1. Create a canonical request
	signedHeaders := "content-md5;host;x-amz-content-sha256;x-amz-date"
	canonicalHeaders := fmt.Sprintf(
		"content-md5:%s\nhost:%s\nx-amz-content-sha256:%s\nx-amz-date:%s\n",
		stringMD5, req.Host, stringSHA, dataAmazon,
	)
	canonicalRequest := fmt.Sprintf("%s\n%s\n%s\n%s\n%s\n%s",
		req.Method,
		req.URL.EscapedPath(),
		req.URL.Query().Encode(),
		canonicalHeaders,
		signedHeaders,
		stringSHA,
	)

	// Step 2: String to sign
	scope := fmt.Sprintf("%s/%s/%s/aws4_request", dateStamp, region, service)
	stringToSign := fmt.Sprintf("AWS4-HMAC-SHA256\n%s\n%s\n%s",
		dataAmazon, scope, sha256HEX([]byte(canonicalRequest)),
	)

	// Step 3: Derive signing key
	kDate := sha256HMAC([]byte("AWS4"+secretKey), []byte(dateStamp))
	kRegion := sha256HMAC(kDate, []byte(region))
	kService := sha256HMAC(kRegion, []byte(service))
	kSigning := sha256HMAC(kService, []byte("aws4_request"))

	// Step 4: Signature
	signature := hex.EncodeToString(sha256HMAC(kSigning, []byte(stringToSign)))
	authHeader := fmt.Sprintf(
		"AWS4-HMAC-SHA256 Credential=%s/%s, SignedHeaders=%s, Signature=%s",
		accessKey, scope, signedHeaders, signature,
	)
	req.Header.Set("Authorization", authHeader)
}

func sha256HEX(data []byte) string {
	h := sha256.Sum256(data)
	return hex.EncodeToString(h[:])
}

func sha256HMAC(key, data []byte) []byte {
	h := hmac.New(sha256.New, key)
	h.Write(data)
	return h.Sum(nil)
}
